load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "dict",
    srcs = glob(["dict/**"]),
)

cc_library(
    name = "marisa",
    srcs = glob(["deps/marisa-trie/lib/marisa/**/*.cc"]),
    hdrs = glob(["deps/marisa-trie/include/**/*.h"]) + glob(["deps/marisa-trie/lib/marisa/**/*.h"]),
    copts = [
        "-std=c++17",
        "-Ideps/marisa-trie/include",
        "-Ideps/marisa-trie/lib",
    ],
    includes = [
        "deps/marisa-trie/include",
        "deps/marisa-trie/lib",
    ],
)

cc_library(
    name = "cppjieba",
    hdrs = glob([
        "include/cppjieba/**/*.hpp",
        "deps/darts-clone/include/**/*.h",
        "deps/marisa-trie/include/**/*.h",
    ]),
    copts = [
        "-std=c++17",
        "-Iinclude",
        "-Ideps/darts-clone/include",
        "-Ideps/marisa-trie/include",
    ],
    includes = [
        "include",
        "deps/darts-clone/include",
        "deps/marisa-trie/include",
    ],
    deps = [":marisa"],
)

cc_test(
    name = "bazel_smoke_test",
    srcs = ["test/bazel_smoke_test.cpp"],
    data = [":dict"],
    deps = [":cppjieba"],
)
